#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: scripts/new-worktree.sh <name> [base-ref]" >&2
  exit 2
fi
name="$1"
base="${2:-HEAD}"

top="$(git rev-parse --show-toplevel)"
parent="$(dirname "$top")"
dest="$parent/ferrox-$name"
shared="${FERROX_TARGET_DIR:-$parent/.ferrox-target}"

if [[ -e "$dest" ]]; then
  echo "::error::$dest already exists" >&2
  exit 1
fi

git -C "$top" worktree add "$dest" -b "$name" "$base"

mkdir -p "$dest/.cargo" "$shared"
{
  echo "# Generated by scripts/new-worktree.sh. Never committed:"
  echo "# every worktree builds here so dependencies compile once."
  echo ""
  echo "[build]"
  echo "target-dir = \"$shared\""
  echo ""
  echo "# Hardware crypto for aarch64 builds, matching ci.yml so a local"
  echo "# measurement is of the code CI ships: the aes and polyval crates"
  echo "# (behind aes-gcm, i.e. every VMess header seal, AES data frame,"
  echo "# auth-id block and Shadowsocks chunk) compile their ARMv8-Crypto"
  echo "# backends only behind these cfgs and then runtime-dispatch, so a"
  echo "# device without the extension runs the soft code it runs today."
  echo "# Measured 12x on a VMess header seal and on a Cipher::Aes data frame."
  echo "# x86_64 consults neither cfg."
  echo "[target.aarch64-apple-darwin]"
  echo "rustflags = [\"--cfg\", \"aes_armv8\", \"--cfg\", \"polyval_armv8\"]"
  echo ""
  echo "[target.aarch64-unknown-linux-gnu]"
  echo "rustflags = [\"--cfg\", \"aes_armv8\", \"--cfg\", \"polyval_armv8\"]"
} > "$dest/.cargo/config.toml"

linked=0
for checkout in "$top"/upstream/*/; do
  checkout="${checkout%/}"
  base_name="$(basename "$checkout")"
  if [[ -d "$checkout/.git" && ! -e "$dest/upstream/$base_name" ]]; then
    ln -s "$checkout" "$dest/upstream/$base_name"
    linked=$((linked + 1))
  fi
done

echo "worktree: $dest (branch $name)"
echo "target-dir: $shared"
echo "upstream checkouts linked: $linked"
echo "next: ./scripts/fetch-upstream.sh (only what the links missed), then ./scripts/check.sh"
